  import type { Metadata } from "next";
  import { Poppins } from "next/font/google";
  import "./globals.css";
  import Header from "@/components/layout/Header";



  const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["400", "600", "700"],
  });

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body
          className={`${poppins.variable} antialiased`}
          style={{ fontFamily: "var(--font-poppins), Arial, sans-serif" }}
          >
          <Header/>
        
          {children}
        </body>
      </html>
    );
  }
